# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/bionic64"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "/tmp/id_rsa.pub"
    config.vm.provision "file", source: "./confs/application.yaml", destination: "/tmp/application.yaml"
    config.vm.provision "file", source: "./confs/argo.yaml", destination: "/tmp/argo.yaml"
    config.vm.provision "file", source: "./confs/ingress.yaml", destination: "/tmp/ingress.yaml"
    config.vm.provision "shell", path: "./scripts/master_script.sh"

    config.ssh.insert_key = false
    config.ssh.private_key_path = [".vagrant.d/insecure_private_key", "~/.ssh/vagrant"]

    config.vm.hostname = "fgoulamaS"
    config.vm.network "private_network", ip: "192.168.56.110"

end
