# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "hashicorp/bionic64"
    config.vm.provision "file", source: "~/.ssh/vagrant.pub", destination: "/tmp/id_rsa.pub"
    config.vm.provision "file", source: "~/.ssh/vagrant", destination: "/tmp/id_rsa"
    config.vm.provision "shell", path: "./common_script.sh"
    config.ssh.insert_key = false
    config.ssh.private_key_path = [".vagrant.d/insecure_private_key", "~/.ssh/vagrant"]

    config.vm.define "master" do |master|
        master.vm.hostname = "fgoulamaS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provision "shell", path: "./master_script.sh"
    end

    config.vm.define "worker" do |worker|
        worker.vm.hostname = "fgoulamaSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provision "shell", path: "./worker_script.sh"
    end

end